version: v1.1.0
stepTimeout: 1800

steps:
  - id: build-api
    build: >
      -t $Registry/{{.Values.imageRepository}}:{{.Run.Commit}}
      -t $Registry/{{.Values.imageRepository}}:main
      -f Dockerfile
      .

  - id: push-api
    push:
      - $Registry/{{.Values.imageRepository}}:{{.Run.Commit}}
      - $Registry/{{.Values.imageRepository}}:main
    when:
      - build-api

  - id: deploy-container-app
    cmd: >
      -c "az login --identity &&
      az containerapp update
      --name {{.Values.containerAppName}}
      --resource-group {{.Values.resourceGroup}}
      --image $Registry/{{.Values.imageRepository}}:{{.Run.Commit}}"
    entryPoint: /bin/sh
    when:
      - push-api
